config/routes.rb
Rails.application.routes.draw do
  
  get 'posts/:id/delete' => 'posts#delete'
  get 'posts/cooking' => 'posts#cooking'

  root 'posts#index'
  resources :posts do
    resources :comments
  end
  #do
  #	resources :comments
  #end
  resources :comments
  get 'post/:id/edit' => 'posts#edit'
  patch 'posts/:id/edit' => 'posts#update'

  #get 'posts/new' => 'posts#new'
  #post 'posts/index' => 'posts#create'

  devise_for :runners
  devise_for :juans, :controllers => { registrations: 'registrations' }
  get 'juans/profile'
  get 'juans/:id' => 'juans#profile'
  post 'juans' => 'juans#create'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/juan.rb
class Juan < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :juan
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :runners
	has_many :comments

	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

	def all_tags=(names)
		self.tags = names.split(", ").map do |name|
			Tag.where(name: name).first_or_create!
		end
	end

	def all_tags
		tags.map(&:name).join(", ")
	end
	
end

app/models/runner.rb
class Runner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings, dependent: :destroy
	has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #def create
  #	@post = Post.find(params[:post][:id])
   # @comment.name = current_runner
  #	@comment = @post.comments.create(params[:comment].permit(:body))
#
 # 	redirect_to post_path(@post)
 # end

 def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
 end



# 	def create
 #		@post = Post.find(params[:post][:id])
 #		@comment = @post.comments.new(params[:comment][:body])
 #		@comment.name = current_runner
#
 #		redirect_to "index"
  #  end
end

app/controllers/juans_controller.rb
class JuansController < ApplicationController
  def profile
  	 @juan = Juan.find(params[:id])
  end

  	def delete
    @post = Post.find(params[:id])
    @post.destroy()

    redirect_to "/juans/<%=current_juan.id%>"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def housekeeper 
      @post = Post.find_by(tags: "houekeeping")
  end 
 
  def cooking
    @post = Post.all
    @post = @post.tags.where(name: "cooking")
  end

  def entertainment
    @post = Post.tags.where(name: "entertainment")
  end

  def games
    @post = Post.tags.where(name: "games")
  end

  def clerk
    @post = Post.tags.where(name: "clerk")
  end

  def others
    @post = Post.tags.where(name: "others")
  end


  def new
  	@post = Post.new
  end

  def create
  	@post = current_juan.posts.new(post_params)
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
  	@post = Post.all
  end

  def delete
    @post = Post.find(params[:id])
    @post.destroy()

    redirect_to 'index' 
  end

   def show
    @post = Post.find(params[:id])
   #  @postco = Post.tags.where(name: "cooking")
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title,:description,:location, :all_tags))
      redirect_to '/posts/'
    else
      render 'edit'
    end

  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :location, :all_tags)
  end

  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:juan).permit(:first_name, :last_name, :email, :contact_number, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:juan).permit(:first_name, :last_name, :email, :contact_number, :password, :password_confirmation, :current_password)
  end

   def sign_up_params
    params.require(:runner).permit(:first_name, :last_name, :email, :contact_number, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:runner).permit(:first_name, :last_name, :email, :contact_number, :password, :password_confirmation, :current_password)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/juans_helper.rb
module JuansHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/comments/_comment.html.erb
 <p><%=comment.name%></p>
 <p><%=comment.body%></p>

app/views/comments/_form.html.erb
<%= form_for ([@post,@post.comments.build]) do |f| %>
<p><%= f.label :name %> </p>
<p><%= f.text_field :name %> </p>
<p><%= f.label :body %> </p>
<p><%= f.text_area :body %> </p>
<br>
<p>
<%= f.submit "Apply" %>
</p>
<%end%>

app/views/comments/create.html.erb
 <%= render 'comments/form'%>

app/views/juans/profile.html.erb
<div style="top: 100px">
<div class = "container"><strong><h2> <%= current_juan.first_name %>, <%= current_juan.last_name%></h2></strong>

 <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Current Jobs Offered</h2>
                    <hr class="star-primary">
                </div>
            </div>
<div class = "container"> 
<% @juan.posts.each do |post| %>
  <div class = "container">
  <span class = "border-0">
  <a href = "/posts/<%= post.id%>"> <%=post.title %></a>

  <br> <%= post.description %> </br>
  <br> <%= post.all_tags %> </br>
  </span>
  </div>
<% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juanrun</title>
    <%= csrf_meta_tags %>

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/freelancer.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/thumbnail-gallery.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav id="mainNav" class="navbar navbar-default navbar-toggleable-md navbar-inverse bg-inverse navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/../../">JuanRun</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <% if current_juan %> 
                    
                      <li class="nav-link">
                        <a href="/juans/<%=current_juan.id%>/">Hi, <%=current_juan.first_name%></a>
                      </li> 
                    <% elsif current_runner %>
                      <li class="nav-link">
                        <a href="/runners/<%=current_runner.id%>/">Hi, <%=current_runner.first_name%></a>
                      </li> 
                      <% else %>
                  <%end%>

                      <li class="nav-link">
                        <a href="/../../">About</a>
                      </li> 
                      <li class="nav-link">
                        <a href="/index">Jobs</a>
                      </li> 
                  
                    <% if current_juan %> 
                    <li class="nav-link">
                        <a href="/posts/new">Add Job</a>
                    </li>
                     <li class="nav-link">
                        <a href="/../juans/edit">Settings</a>
                    </li>
                    <li class = "nav-link">
                    <%= link_to "Log out", destroy_juan_session_path, method: :delete, data: {confirm: "Are you sure?" }%>
                    </li>

                     <%elsif current_runner %> 
                     <li class="nav-link">
                        <a href="/../runners/edit">Settings</a>
                    </li>
                      
                    <li class = "nav-link">
                    <%= link_to "Log out", destroy_juan_session_path, method: :delete, data: {confirm: "Are you sure?" }%>
                    </li>
                <% else %>
                <li class="dropdown">
                 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign Up
                 <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                   <li><a href="/juans/sign_up">Juan</a></li>
                  <li><a href="runners/sign_up">Runner</a></li>
                 </ul>
                </li>
                  <li class="dropdown">
                 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign In
                 <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                   <li><a href="/juans/sign_in">Juan</a></li>
                  <li><a href="runners/sign_in">Runner</a></li>
                 </ul>
                </li>
             <% end %>
                </ul>
            </div>   <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
  <div class = "container">
  <p class = "notice"><%= notice %> </p>
  <p class = "alert"> <% alert %> </p>
    <%= yield %>
  </div>
    
  </body>
  
</html>

app/views/posts/_form.html.erb
<div class = "container">
<div id = "page_wrapper">
<%= form_for @post do |f| %>
<p><%= f.label :title %> <%= f.text_field :title %> </p>
<p><%= f.label :description %> <%= f.text_area :description %></p>
<p><%= f.label :location %> <%= f.text_field :location %></p>
<p><%= f.label :all_tags %> <%= f.text_field :all_tags %></p>
<%= f.submit "Publish Job" %>
<% end %>
</div>
</div>

app/views/posts/cooking.html.erb
<%= @post.each do |post| %>
	<%= post.title %>
	<%= post.description %>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1 class = "title">Edit Post</h1>
<%= render 'form' %>

app/views/posts/games.html.erb
games

app/views/posts/index.html.erb
<% @post.each do |f| %>
 <div class = "container">
 <span class = "border-0">
 <table>
 <tr>
 <td><strong>Job Title:</strong> </td><td><%= f.title %></td> 
 </tr>
 <tr>
 <td><strong>Job location:</strong></td><td> <%= f.location %> </td> 
 </tr>
 <tr>
 <td><strong>Job Description:</strong></td><td> <%= f.description %> </td>
 </tr><tr>
 <% if current_runner %>
    <button class = "button"><a href = "posts/<%= f.id %>"> Apply  </a></button>
</tr>
 
 <% end %>
 </table>
</span>
</div>
<% end %>

<section id ="work-gallery">
<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Work Gallery</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="img/portfolio/cabin.png" class="img-responsive" alt="Housekeeping">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <a href = "/posts/cooking"><img src="img/portfolio/cake.png" class="img-responsive" alt="Cooking"></a>
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="img/portfolio/circus.png" class="img-responsive" alt="Entertainment">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="img/portfolio/game.png" class="img-responsive" alt="Games">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="img/portfolio/safe.png" class="img-responsive" alt="Clerk">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="img/portfolio/submarine.png" class="img-responsive" alt="Others">
                    </a>
                </div>
            </div>
        </div>
        </section>
        <p>
        <p>
        <p>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div id = "post_content">
<p> </p>
<h1 class = "title"><%= @post.title %> </h1>

<p class = "date">
Submiited <%= time_ago_in_words(@post.created_at) %> Ago
<% if current_juan %>
<%= link_to 'Edit', edit_post_path(@post) %>
<a href = "/posts/<%= @post.id%>/delete" confirm = "Are you sure you want to delete this job?"> Close Job </a>
<% end %>
</p>


<p>Job location: <%= @post.location %> </p>
<p class = "body">
 <%= @post.description %> </p>
<% if current_juan %>
 <h2> <%= @post.comments.count %> runners are interested in this job </h2>
 <%= render @post.comments %>
 <% elsif current_runner %>
  <%= render 'comments/form'%>
  <% else %>
<% end %>
